// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TextParcel struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextParcel) Reset()         { *m = TextParcel{} }
func (m *TextParcel) String() string { return proto.CompactTextString(m) }
func (*TextParcel) ProtoMessage()    {}
func (*TextParcel) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_9f7d1549a6149c10, []int{0}
}
func (m *TextParcel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextParcel.Unmarshal(m, b)
}
func (m *TextParcel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextParcel.Marshal(b, m, deterministic)
}
func (dst *TextParcel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextParcel.Merge(dst, src)
}
func (m *TextParcel) XXX_Size() int {
	return xxx_messageInfo_TextParcel.Size(m)
}
func (m *TextParcel) XXX_DiscardUnknown() {
	xxx_messageInfo_TextParcel.DiscardUnknown(m)
}

var xxx_messageInfo_TextParcel proto.InternalMessageInfo

func (m *TextParcel) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_9f7d1549a6149c10, []int{1}
}
func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (dst *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(dst, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TextParcel)(nil), "pb.TextParcel")
	proto.RegisterType((*Void)(nil), "pb.Void")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VpnkitManagerClient is the client API for VpnkitManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VpnkitManagerClient interface {
	Ping(ctx context.Context, in *Void, opts ...grpc.CallOption) (*TextParcel, error)
}

type vpnkitManagerClient struct {
	cc *grpc.ClientConn
}

func NewVpnkitManagerClient(cc *grpc.ClientConn) VpnkitManagerClient {
	return &vpnkitManagerClient{cc}
}

func (c *vpnkitManagerClient) Ping(ctx context.Context, in *Void, opts ...grpc.CallOption) (*TextParcel, error) {
	out := new(TextParcel)
	err := c.cc.Invoke(ctx, "/pb.VpnkitManager/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VpnkitManagerServer is the server API for VpnkitManager service.
type VpnkitManagerServer interface {
	Ping(context.Context, *Void) (*TextParcel, error)
}

func RegisterVpnkitManagerServer(s *grpc.Server, srv VpnkitManagerServer) {
	s.RegisterService(&_VpnkitManager_serviceDesc, srv)
}

func _VpnkitManager_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnkitManagerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VpnkitManager/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnkitManagerServer).Ping(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _VpnkitManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VpnkitManager",
	HandlerType: (*VpnkitManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _VpnkitManager_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_messages_9f7d1549a6149c10) }

var fileDescriptor_messages_9f7d1549a6149c10 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52,
	0xe2, 0xe2, 0x0a, 0x49, 0xad, 0x28, 0x09, 0x48, 0x2c, 0x4a, 0x4e, 0xcd, 0x11, 0x12, 0xe1, 0x62,
	0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x94, 0xd8,
	0xb8, 0x58, 0xc2, 0xf2, 0x33, 0x53, 0x8c, 0x0c, 0xb9, 0x78, 0xc3, 0x0a, 0xf2, 0xb2, 0x33, 0x4b,
	0x7c, 0x13, 0xf3, 0x12, 0xd3, 0x53, 0x8b, 0x84, 0x14, 0xb8, 0x58, 0x02, 0x32, 0xf3, 0xd2, 0x85,
	0x38, 0xf4, 0x0a, 0x92, 0xf4, 0x40, 0x4a, 0xa4, 0xf8, 0x40, 0x2c, 0x84, 0x81, 0x49, 0x6c, 0x60,
	0x9b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xda, 0xcb, 0x58, 0x29, 0x7b, 0x00, 0x00, 0x00,
}
